# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mg < Formula
  desc "CLI tool for managing stacked PRs"
  homepage "https://github.com/mrge-io/mg-cli"
  version "1.0.32"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrge-io/homebrew-tap/releases/download/v1.0.32/mg_1.0.32_darwin_x86_64.tar.gz"
      sha256 "150b8d2db072147795e7d7f78f2621f7d25fe1aeb83b33222fb4bbdd4c804739"

      def install
        bin.install "mg"
        # Install shell completions
        generate_completions_from_executable(bin/"mg", "completion", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrge-io/homebrew-tap/releases/download/v1.0.32/mg_1.0.32_darwin_arm64.tar.gz"
      sha256 "eead9a4f8cbefaa8702e11a1e0088e8dfb22a372399595f84811f0e5e83eb992"

      def install
        bin.install "mg"
        # Install shell completions
        generate_completions_from_executable(bin/"mg", "completion", shells: [:bash, :zsh])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mrge-io/homebrew-tap/releases/download/v1.0.32/mg_1.0.32_linux_x86_64.tar.gz"
        sha256 "d295e99f7a33347f5103e03b1e05b6574c83b800e88be11fd5e55873a6283a05"

        def install
          bin.install "mg"
          # Install shell completions
          generate_completions_from_executable(bin/"mg", "completion", shells: [:bash, :zsh])
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mrge-io/homebrew-tap/releases/download/v1.0.32/mg_1.0.32_linux_arm64.tar.gz"
        sha256 "d5294c350e050bd07ce012d9e27d7c96dac74742e1d4bd949bd636c3ba91a9eb"

        def install
          bin.install "mg"
          # Install shell completions
          generate_completions_from_executable(bin/"mg", "completion", shells: [:bash, :zsh])
        end
      end
    end
  end
end
